### PR TITLE
Add conversion between transform 2d and 3d

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Merge before https://github.com/tue-robotics/ed_localization/pull/15

### CODE REVIEW

**Review by PetervDooren — CHANGES_REQUESTED** [review]
I dont like this. Here you always assume that the z direction is the one to be flattened. That is a decision which does not belong in this package. I suggest you implement these functions where you need them.

**Comment by MatthijsBurgh** [comment]
I think the assumption of the z direction being flattened is a good assumption. If somebody wants to flatten any other direction, he/she can do it manually.

Might be good to add some docstrings.

**Comment by PetervDooren** [comment]
The assumption you're making is that z is the direction perpendicular to the floor.
In this case flattening z is a logical thing to do. But geolib contains mathematical objects only, it has no concept of floor. Some people use y as being perpendicular to the floor.
So I think if someone wants to flatten any direction they should do it manually.

**Comment by MatthijsBurgh** [comment]
I can understand you don't agree with the custom copy constructors and =operator. But I think a good alternative is to add projectTo2d and projectTo3d functions to Transform3d and Transform2d respectively. Maybe also to the Vec classes.

**Comment by MatthijsBurgh** [comment]
@PetervDooren ping

**Review by PetervDooren — APPROVED** [review]

**Pull request merged**
