### PR TITLE
fix(CMakeList.txt): solved opencv build error

### PR DESCRIPTION
**Pull request by TankPi**
We had a build error using your geolib2 package regarding the decency on the latest opencv. This change in the CMakeList.txt solved our issue.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@reinzor, @Timple you know much more about CMake than I do, could you please review?

**Comment by MatthijsBurgh** [comment]
@Timple Would you be able to review this?

**Comment by Timple** [comment]
Sure, I'll take a peek tomorrow.

@TankPi Did you keep a copy of the build error? It would be nice to reproduce first :)
And could you post a source of your code snippet? Or if self-made: add a comment line on what it does?

**Comment by Timple** [comment]
Unable to reproduce in a docker environment.

```bash
$ opencv_version 
3.3.1-dev
```

compiles just fine.

Steps to reproduce:
```
wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/install-package.sh
wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/build-package.sh
install-package.sh --package=geolib2

#Check opencv version
docker exec -it tue-env bash -c "export CI='true'; source /home/amigo/.bashrc; opencv_version"

#Check compilation
build-package.sh --package=geolib2
```

**Review by Timple — CHANGES_REQUESTED** [review]
Need to reproduce issue first, 3.3.1-dev seems to compile fine.

**Comment by MatthijsBurgh** [comment]
@TankPi, please review the comments of @Timple

**Comment by MatthijsBurgh** [comment]
@TankPi Please respond to comments of @Timple. Otherwise I will be closing this PR.

**Pull request closed without merging**
